[package]
name = "marketParser"
version = "0.1.0"
authors = ["conner <connersmith84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap-file = "0.10.0"
chrono = "0.4.19"
multimap = "0.6.0"
